name: Build

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    tags-ignore:
      - r[0-9]*
  workflow_dispatch:

jobs:
  Build:
    uses: evanchooly/workflows/.github/workflows/build.yml@master
    with:
      java: 17

  Snapshots:
    if: github.ref_type == 'branch'
    needs:
      - Build
    uses: evanchooly/workflows/.github/workflows/release.yml@master
    secrets:
      JRELEASER_NEXUS2_USERNAME: ${{ secrets.JRELEASER_NEXUS2_USERNAME }}
      JRELEASER_NEXUS2_PASSWORD: ${{ secrets.JRELEASER_NEXUS2_PASSWORD }}
      JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
