name: Build

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  CodeAudits:
    uses: evanchooly/workflows/.github/workflows/code-audits.yml@master

  Build:
    uses: evanchooly/workflows/.github/workflows/build.yml@master
    with:
      java: 17

  Release:
    if: github.ref_type == 'branch' || github.ref_type == 'tag'
    needs:
      - Build
      - CodeAudits
    uses: evanchooly/workflows/.github/workflows/jreleaser.yml@master
    with:
      java: 17
    secrets:
      GH_PUSH_TOKEN       : ${{ secrets.GH_PUSH_TOKEN }}
      GPG_PASSPHRASE      : ${{ secrets.GPG_PASSPHRASE }}
      GPG_PUBLIC_KEY      : ${{ secrets.GPG_PUBLIC_KEY }}
      GPG_PRIVATE_KEY     : ${{ secrets.GPG_PRIVATE_KEY }}
      SONATYPE_USERNAME   : ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD   : ${{ secrets.SONATYPE_PASSWORD }}
