name: Release

on:
  push:
    tags:
      - r[0-9]*
  workflow_dispatch:

jobs:
  release:
    uses: evanchooly/workflows/.github/workflows/release.yml@master
    with:
      java: 17
    secrets:
      BLUESKY_PASSWORD: ${{secrets.BLUESKY_PASSWORD }}
      BLUESKY_USERNAME: ${{secrets.BLUESKY_USERNAME }}
      JRELEASER_GITHUB_TOKEN: ${{secrets.JRELEASER_GITHUB_TOKEN }}
      JRELEASER_GPG_PASSPHRASE: ${{secrets.JRELEASER_GPG_PASSPHRASE }}
      JRELEASER_GPG_PUBLIC_KEY: ${{secrets.JRELEASER_GPG_PUBLIC_KEY }}
      JRELEASER_GPG_SECRET_KEY: ${{secrets.JRELEASER_GPG_SECRET_KEY }}
      JRELEASER_NEXUS2_PASSWORD: ${{secrets.JRELEASER_NEXUS2_PASSWORD }}
      JRELEASER_NEXUS2_USERNAME: ${{secrets.JRELEASER_NEXUS2_USERNAME }}
      MASTODON_ACCESS_KEY: ${{secrets.MASTODON_ACCESS_KEY }}
